OBJS += aarch64/cpu.o                                                 \
        aarch64/float_dsp_init.o                                      \
        aarch64/aes_init.o                                            \

ARMV8-OBJS += aarch64/aes.o

NEON-OBJS += aarch64/float_dsp_neon.o
